# Generated by Django 2.2.5 on 2021-01-08 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workoutlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
